const assert = require("node:assert/strict");
const { createScrobbleController, COMPLETED_KEY, NEGATIVE_TTL } = require("../playback/scrobble-controller.js");
let stored = {};
const storage = { async get(key) { return { [key]: stored[key] }; }, async set(value) { Object.assign(stored, value); } };
const calls = [];
const client = { async scrobble(action, item, progress) { calls.push({ action, id: item.traktId, progress }); return { action: action === "stop" ? "scrobble" : action }; } };
const matcher = { async match({ media }) { const id = media.title === "Two" ? 2 : 1; return { status: "matched", key: `movie:${id}`, item: { type: "movie", traktId: id } }; } };
const source = (tabId, frameId = 0) => ({ tabId, frameId, url: `https://site${tabId}.test/watch`, hostname: `site${tabId}.test`, pageTitle: "Page" });
const status = (title, progress, state, tabId = 1, frameId = 0, extra = {}) => ({ kind: "media", source: source(tabId, frameId), media: { title, artist: null, album: null, duration: 100, progress, state, ...extra } });

(async () => {
  const controller = createScrobbleController({ matcher, client, isConnected: async () => true, storage, now: () => 1234 });
  await controller.handle(status("One", 10, "playing"));
  await controller.handle(status("One", 20, "playing", 2));
  assert.deepEqual(calls.map(({ action, id }) => [action, id]), [["start", 1], ["pause", 1], ["start", 1]], "replacement pauses prior global winner before start");
  await controller.handle(status("Two", 30, "playing", 2));
  assert.deepEqual(calls.slice(-2).map(({ action, id }) => [action, id]), [["pause", 1], ["start", 2]], "SPA metadata invalidates old match");
  await controller.handle(status("Two", 85, "playing", 2));
  assert.equal(stored[COMPLETED_KEY]["movie:2"], 1234);
  assert.equal(controller.statusFor(source(2)).state, "synced");
  const afterStop = calls.length;
  await controller.handle(status("One", 90, "playing", 2));
  assert.deepEqual(calls.slice(afterStop).map(({ action, id }) => [action, id]), [["stop", 1]], "completed items are never paused during winner replacement");
  await controller.handle({ kind: "empty" });
  assert.equal(controller.statusFor(source(2)).state, "idle");

  let time = 1000;
  let attempts = 0;
  const negative = createScrobbleController({ matcher: { async match() { attempts++; return { status: "unmatched" }; } }, client, isConnected: async () => true, storage: { async get(){return{};},async set(){} }, now: () => time });
  await negative.handle(status("Missing", 10, "playing", 3, 0, { duration: 100 }));
  const cosmeticChange = status("Missing", 20, "playing", 4, 0, { duration: 200 });
  cosmeticChange.source.pageTitle = "Changing page title";
  await negative.handle(cosmeticChange);
  assert.equal(attempts, 1, "page title, source, and duration changes cannot bypass negative cooldown");
  await negative.handle(status("Changed", 20, "playing", 4));
  assert.equal(attempts, 2, "title change retries immediately");
  time += NEGATIVE_TTL + 1;
  await negative.handle(status("Missing", 30, "playing", 4));
  assert.equal(attempts, 3, "deterministic result retries after cooldown");

  let pageMatches = 0;
  const pageAware = createScrobbleController({ matcher: { async match({ pageTitle }) { pageMatches++; const id = pageTitle === "Episode 2" ? 2 : 1; return { status: "matched", key: `episode:${id}`, item: { type: "episode", traktId: id } }; } }, client, isConnected: async () => true, storage: { async get(){return{};},async set(){} } });
  const firstPage = status("Generic", 10, "playing", 9); firstPage.source.pageTitle = "Episode 1";
  const secondPage = status("Generic", 10, "playing", 9); secondPage.source.pageTitle = "Episode 2";
  await pageAware.handle(firstPage);
  await pageAware.handle(secondPage);
  assert.equal(pageMatches, 2, "page-title episode changes invalidate matched SPA media");

  let retryTime = 1000;
  let retryAttempts = 0;
  const retrying = createScrobbleController({ matcher: { async match() { retryAttempts++; throw { status: 429, retryAfter: 5000 }; } }, client, isConnected: async () => true, storage: { async get(){return{};},async set(){} }, now: () => retryTime });
  await retrying.handle(status("Limited", 10, "playing", 6));
  await retrying.handle(status("Limited", 20, "playing", 6));
  assert.equal(retryAttempts, 1, "429 retry-after suppresses early retry");
  retryTime = 5000;
  await retrying.handle(status("Limited", 30, "playing", 6));
  assert.equal(retryAttempts, 2, "429 retries at deadline");

  let terminalAttempts = 0;
  const terminal = createScrobbleController({ matcher: { async match() { terminalAttempts++; throw { status: 422 }; } }, client, isConnected: async () => true, storage: { async get(){return{};},async set(){} } });
  await terminal.handle(status("Invalid", 10, "playing", 7));
  await terminal.handle(status("Invalid", 20, "playing", 7));
  assert.equal(terminalAttempts, 1, "terminal API failure uses negative cooldown");

  let releaseUnauthorized;
  let unauthorizedFinished = false;
  let unauthorizedScrobbles = 0;
  const unauthorized = createScrobbleController({ matcher, client: { async scrobble() { if (++unauthorizedScrobbles === 1) throw { status: 401 }; return { action: "start" }; } }, isConnected: async () => true, storage: { async get(){return{};},async set(){} }, onUnauthorized: () => new Promise((resolve) => { releaseUnauthorized = () => { unauthorizedFinished = true; resolve(); }; }) });
  const unauthorizedTask = unauthorized.handle(status("One", 10, "playing", 8));
  while (!releaseUnauthorized) await Promise.resolve();
  let unauthorizedSettled = false;
  unauthorizedTask.then(() => { unauthorizedSettled = true; });
  await Promise.resolve();
  assert.equal(unauthorizedSettled, false, "event work awaits unauthorized cleanup");
  releaseUnauthorized();
  await unauthorizedTask;
  assert.equal(unauthorizedFinished, true);
  await unauthorized.handle(status("One", 20, "playing", 8));
  assert.equal(unauthorizedScrobbles, 1, "401 suspends processing until reconnect");
  unauthorized.resume();
  await unauthorized.handle(status("One", 20, "playing", 8));
  assert.equal(unauthorizedScrobbles, 2, "successful reconnect resumes same selection without five-minute lock");

  let releaseSet;
  let writes = 0;
  const slowStorage = { async get(){return{};}, set() { writes++; return new Promise((resolve) => { releaseSet = resolve; }); } };
  const slow = createScrobbleController({ matcher, client, isConnected: async () => true, storage: slowStorage });
  const completion = slow.handle(status("One", 85, "playing", 5));
  while (!releaseSet) await Promise.resolve();
  const reset = slow.reset();
  let resetDone = false;
  reset.then(() => { resetDone = true; });
  await Promise.resolve();
  assert.equal(resetDone, false, "reset awaits old completion write queue");
  releaseSet();
  await Promise.all([completion, reset]);
  assert.equal(writes, 1);
  const callsBeforeSuspended = calls.length;
  await slow.handle(status("Two", 10, "playing", 5));
  assert.equal(calls.length, callsBeforeSuspended, "reset suspends new observations during disconnect");
  console.log("scrobble controller checks: OK");
})().catch((error) => { console.error(error); process.exitCode = 1; });
